# Generated by Django 4.2.20 on 2025-09-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notifications_email',
            field=models.BooleanField(default=True, help_text='Customer wants email notifications'),
        ),
        migrations.AddField(
            model_name='order',
            name='notifications_sms',
            field=models.BooleanField(default=True, help_text='Customer wants SMS notifications'),
        ),
    ]
